config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'users/show'
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users

  resources :posts do
    resources :reviews, except: [:index, :show, :edit, :update]
  end

  resources :posts do
      resources :likes, only: [:create, :destroy]
    end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, counter_cache: :likes_count
  belongs_to :post, counter_cache: :likes_count
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :body, presence: true, length: { maximum: 1000 }

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :post, counter_cache: :reviews_count
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 500 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  attribute :new_avatar

  has_many :posts, dependent: :destroy
  validates :nick_name, presence: true


  before_save do
    self.image = new_avatar if new_avatar
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]


  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: "投稿しました。"
    else
      render new_post_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.user_id == current_user.id
      @post.update(post_params)
      redirect_to @post, notice: "編集しました"
    else
      redirect_to @post, alert: "編集権限がありません"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "削除しました"
  end

  private

    def post_params
      params.require(:post).permit(:body)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
# app/controllers/reviews_controller.rb

class ReviewsController < ApplicationController
  before_action :set_post, only: [:new, :create, :destroy]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.attributes = {
      post_id: params[:post_id],
      user_id: current_user.id
    }
    if @review.save
      redirect_to @review.post, notice: "レビューを登録しました。"
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @review.post, notice: "レビューを削除しました。"
  end

  private

  def review_params
    params.require(:review).permit(:comment)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def like_status
    case current_user.likes_count
    when 0..100
      return "F"
    when 101..200
      return "E"
    when 201..400
      return "D"
    when 401..600
      return "C"
    when 601..900
      return "B"
    when 901..1200
      return "B+"
    when 1201..1500
      return "A"
    when 1501..2000
      return "A+"
    when 2001..2500
      return "S"
    when 2501..3000
      return "S+"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="jumbotron col-md-12 mt-3">
  <h1>Cheer Appへようこそ</h1>
  <div class="mb-5">
    <p>
      このアプリは褒めることに特化したSNSです。<br>
      褒められたいことを投稿して、いいねをもらって元気をもらいましょう。
    </p>
  </div>
  <h2 class="my-3">Concept</h2>
  <div>
    <p>
      子供のころはご飯を残さず食べたからとほめられた。<br>
      社会人になると日常生活においてほめられることは稀です。<br>
      プログラマーがどんなに素晴らしいコードを書こうが、<br>
      主婦がどんなに美味しい食事を作ろうが感謝される機会はごくごく少ないのである。<br>
      そこで私たちは裏方さんを中心にいつも頑張っているあの方たちへ<br>
      感謝の気持ちをコンセプトにこの「ほめられサロン」を制作しました。
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheer App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <% if user_signed_in? %>
        <div class="row">
          <div class="col-md-8">
            <div class="row">
              <%= yield %>
            </div>
          </div>
          <!-- <div class="col-md-1 bg-dark ml-2"></div> -->
          <div class="col-md-4 border-left" width=100% >
            <div class="row pl-3">
              <%= render 'shared/profile' %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="row">
          <%= yield %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>


  <% unless post.likes_count == 0 %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true, class: "btn" do %>
    <div class="vertical_like">
      <i class="material-icons red-text">favorite</i>
      <span class="red-text">
        <%= "#{post.likes_count}いいね" %>
      </span>
    </div>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true, class: "btn" do %>
    <div class="vertical_like">
      <i class="material-icons grey-text text-darken-2">favorite_border</i>
      <span class="grey-text text-darken-2">
        <%= "#{post.likes_count}いいね" %>
      </span>
    </div>
    <% end %>
  <% end %>

<% else %>

  <% unless post.likes_count == 0 %>
    <div class="vertical_like">
      <i class="material-icons red-text">favorite</i>
      <span class="red-text">
        <%= "#{post.likes_count}いいね" %>
      </span>
    </div>
  <% else %>
    <div class="vertical_like">
      <i class="material-icons grey-text text-darken-2">favorite_border</i>
      <span class="grey-text text-darken-2">
        <%= "#{post.likes_count}いいね" %>
      </span>
    </div>
  <% end %>

<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/_form.html.erb
<!-- app/views/books/_form.html.erb -->

<%= form_with model: post, local: true do |form| %>
  <%= render "shared/errors", obj: post %>
  <div class="form-group">
    <%= form.text_area :body, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<!-- app/views/books/new.html.erb -->

<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">編集する</h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="col-12">
<% @posts.each do |post| %>
  <div class="row border-bottom mb-4">
    <div class="col-md-2">
      <% if post.user.avatar.attached? %>
        <%= image_tag post.user.avatar.variant(resize: "120x120"), class: "img-thumbnail" %>
      <% else %>
        <%= image_tag "no_image.png", width: 120, class: "img-thumbnail" %>
      <% end %>
    </div>
    <div class="col-md-10 pr-2">
      <h4><%= post.user.nick_name %></h4>
      <hr width=90%>
      <%= link_to post, class: "btn text-dark col-md-12 text-left" do %>
        <%= simple_format post.body, class: "mt-2" %>
      <% end %>
      <p class="text-right"><%= post.created_at.strftime("%Y年%m月%d日%H時%M分") %></p>
    </div>

    <div id="likes_buttons_<%= post.id %>">
      <%= render partial: 'likes/like', locals: { post: post, likes: @likes} %>
    </div>
    <% if post.reviews_count.to_i > 0 %>
      <%= link_to "#{post.reviews_count}件のコメント", post, class: "btn btn-default text-dark" %>
      <br>
    <% end %>
  </div>

  <!--  <%= link_to "詳しく見る", post, class: "btn btn-primary btn-sm mt-2"%> %>  -->
<% end %>
</div>

app/views/posts/new.html.erb
<!-- app/views/books/new.html.erb -->

<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">新しい投稿</h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<!-- app/views/posts/show.html.erb -->

<div class="col-md-10 offset-md-1 mt-5">
  <h4>投稿</h4>
  <div class="row border-bottom">
    <div class="col-md-2">
      <% if @post.user.avatar.attached? %>
        <%= image_tag @post.user.avatar.variant(resize: "120x120"), class: "img-thumbnail" %>
      <% else %>
        <%= image_tag 'no_image.png', width: 120, class: "img-thumbnail" %>
      <% end %>
    </div>
    <div class="col-md-10 pr-4">
      <h4><%= @post.user.nick_name %></h4>
      <% if user_signed_in? && @post.user_id == current_user.id %>
        <%= link_to "編集", edit_post_path(@post), class: "btn btn-primary mt-2" %>
        <%= button_tag "削除", class: "btn btn-warning mt-2", data: { toggle: "modal", target: "#delete-post" } %>
      <% end %>
      <hr>
      <%= simple_format @post.body, class: "mt-2" %>
      <p class="text-right"><%= @post.created_at.strftime("%Y年%m月%d日%H時%M分") %></p>
    </div>
    <div id="likes_buttons_<%= @post.id %>">
      <%= render partial: 'likes/like', locals: { post: @post, likes: @likes} %>
    </div>
  </div>
  <% if user_signed_in? && @post.user_id == current_user.id %>
    <%= link_to "コメントする", new_post_review_path(@post), class: "btn btn-info my-2" %>
  <% elsif user_signed_in? %>
    <%= link_to "褒める", new_post_review_path(@post), class: "btn btn-info my-2" %>
  <% end %>

  <div class="row mt-3">
    <%= render partial: "reviews/review", collection: @post.reviews %>
  </div>
  
  <%= link_to "戻る", posts_path, class: "btn btn-secondary mt-2" %>
</div>

<div class="modal fade" id="delete-post">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">注意</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= "キャンセル" %></button>
        <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<!-- app/views/reviews/_form.html.erb -->

<%= form_with model: [post, review], local: true do |form| %>
  <%= render "shared/errors", obj: review %>
  <div class="form-group">
    <%= form.text_area :comment, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to "戻る", post, class: "btn btn-secondary" %>
<% end %>

app/views/reviews/_review.html.erb
<!-- app/views/reviews/_review.html.erb -->

<div class="col-md-10 offset-md-1 my-2">
  <div>
    <% if review.user.avatar.attached? %>
      <%= image_tag review.user.avatar.variant(resize: "60x60"), class: "img-thumbnail" %>
    <% else %>
      <%= image_tag "no_image.png", class: "img-thumbnail", width: 60 %>
    <% end %>
    <span><%= review.user.nick_name %></span>
    <% if user_signed_in? && current_user.id == @post.user_id || user_signed_in? && current_user.id == review.user_id %>
      <p class="text-right"><%= button_tag "削除", class: "btn btn-sm btn-warning", data: { toggle: "modal", target: "#delete-review" } %></p>
    <% end %>
  </div>
  <%= simple_format review.comment %>
  <hr>
</div>

<div class="modal fade" id="delete-review">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= "注意" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= "キャンセル" %></button>
        <%= link_to "削除", post_review_path(@post, review), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<!-- app/views/reviews/new.html.erb -->

<div class="col-md-8 offset-md-2 mt-3">
  <h2 class="text-center">コメント</h2>
  <%= render partial: 'form', locals: { post: @post, review: @review } %>
</div>

app/views/shared/_errors.html.erb
<!-- app/views/shared/_errors.html.erb -->

<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<!-- app/views/shared/_flash.html.erb -->

<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<!-- app/views/shared/_header.html.erb -->
<nav class="navbar navbar-expand-lg navbar-light mb-3 border-bottom">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Cheer App", root_path, class: "navbar-brand mx-3", id: "header-logo" %>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0 mr-3">
      <li class="nav-item mx-3">
        <%= link_to "Home", root_path, class: "nav-link text-info" %>
      </li>
      <li class="nav-item mx-3">
        <%= link_to "About", 'home/about', class: "nav-link text-info" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item mx-3">
          <%= link_to "ほめられる", new_post_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item mx-3">
          <%= link_to "編集する", edit_user_registration_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item mx-3">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-info" %>
        </li>
      <% else %>
        <li class="nav-item mx-3">
          <%= link_to "アカウント登録", new_user_registration_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item mx-3">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link text-info" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_profile.html.erb
<% if user_signed_in? %>
  <div class="text-center bg-light col-md-12">
    <div></div>
    <h3><%= current_user.nick_name %></h3>
    <br>
    <p>いいねした数<%= current_user.likes_count %></p>
    <p>称号： <%= like_status %></p>
  </div>
<% end %>